import { ICard } from "types/types";

const cardsContent: any = [
  {
    id: 1,
    word: "տուն",
    wordTranslation: "дом",
    phonetics: "tun",
    sentence: "Ես ապրում եմ այդ սպիտակ տանը:",
    sentenceTranslation: "Я живу в том белом доме.",
    img: "house.jpg",
  },
  {
    id: 2,
    word: "աչք",
    wordTranslation: "глаз",
    phonetics: "ach’k’",
    sentence: "Լիլիթը սև աչքեր ունի:",
    sentenceTranslation: "У Лилит черные глаза.",
    img: "eye.jpg",
  },
  {
    id: 3,
    word: "կյանքը",
    wordTranslation: "жизнь",
    phonetics: "kyank’y",
    sentence: "Կյանքը անիմաստ է առանց գարեջուր:",
    sentenceTranslation: "Жизнь бессмысленна без пива.",
    img: "life.jpg",
  },
  {
    id: 4,
    word: "ուրախություն",
    wordTranslation: "счастье",
    phonetics: "urakhut’yun",
    sentence: "Երջանկությունը կարևոր զգացմունք է:",
    sentenceTranslation: "Счастье - важная эмоция.",
    img: "joy.jpg",
  },
  {
    id: 5,
    word: "քաղաք",
    wordTranslation: "город",
    phonetics: "k’aghak",
    sentence: "Ինչպիսի ֆիլմեր ես դու սիրում:",
    sentenceTranslation: "Я родился в небольшом городе.",
    img: "city.jpg",
  },
  {
    id: 6,
    word: "ֆիլմ",
    wordTranslation: "фильм",
    phonetics: "film",
    sentence: "Ես ծնվել եմ փոքրիկ քաղաքում:",
    sentenceTranslation: "Какие фильмы ты любишь смотреть?",
    img: "film.jpg",
  },
  {
    id: 7,
    word: "գնել",
    wordTranslation: "купить",
    phonetics: "gnel",
    sentence: "Որտեղ կարող եմ ջուր գնել:",
    sentenceTranslation: "Где я могу купить воды?",
    img: "buy.jpg",
  },
  {
    id: 8,
    word: "գինի",
    wordTranslation: "вино",
    phonetics: "gini",
    sentence: "Փորձեք այս կարմիր գինին:",
    sentenceTranslation: "Попробуй это красное вино.",
    img: "wine.jpg",
  },
  {
    id: 9,
    word: "թեյ",
    wordTranslation: "чай",
    phonetics: "t’ey",
    sentence: "Խնդրում եմ թեյ առանց շաքարի:",
    sentenceTranslation: "Чай без сахара, пожалуйста.",
    img: "tea.jpg",
  },
  {
    id: 10,
    word: "ծաղիկ",
    wordTranslation: "цветок",
    phonetics: "tsaghik",
    sentence: "Ես իմ սենյակում ծաղիկ ունեմ:",
    sentenceTranslation: "У меня в комнате есть цветок.",
    img: "flower.jpg",
  },
];

export { cardsContent };
